In [3]:
import pandas as pd
import numpy as np

In [2]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [4]:
pd.DataFrame(np.random.rand(5, 5),
             columns =['A', 'B', 'C', 'D', 'E'],
             index = [1, 2, 3, 4, 5])

A         B         C         D         E
1  0.194968  0.275871  0.921912  0.845467  0.956571
2  0.159629  0.263145  0.295891  0.219096  0.157035
3  0.391946  0.574886  0.394285  0.754035  0.374137
4  0.590148  0.298470  0.005946  0.776189  0.612477
5  0.768183  0.221384  0.030499  0.664092  0.413553

In [7]:
pop_tuple = {'서울특별시': 9720846,
             '부산광역시': 3404424,
             '인천광역시': 2947217,
             '대전광역시': 1471040,
             '광주광역시': 14455048}

population = pd.Series(pop_tuple)
population


서울특별시     9720846
부산광역시     3404424
인천광역시     2947217
대전광역시     1471040
광주광역시    14455048
dtype: int64

In [5]:
male_tuple = {'서울특별시': 4732275,
             '부산광역시': 1668618,
             '인천광역시': 1476813,
             '대전광역시': 734441,
             '광주광역시': 720060}

male = pd.Series(male_tuple)
male


서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대전광역시     734441
광주광역시     720060
dtype: int64

In [6]:
female_tuple = {'서울특별시': 4988571,
              '부산광역시': 1735805,
              '인천광역시': 1470404,
              '대전광역시': 1229139,
              '광주광역시': 734988}

female = pd.Series(female_tuple)
female


서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대전광역시    1229139
광주광역시     734988
dtype: int64

In [9]:
korea_df = pd.DataFrame({'인구수': population,
                         '남자인구수': male,
                         '여자인구수':female})
korea_df

인구수    남자인구수    여자인구수
서울특별시   9720846  4732275  4988571
부산광역시   3404424  1668618  1735805
인천광역시   2947217  1476813  1470404
대전광역시   1471040   734441  1229139
광주광역시  14455048   720060   734988

In [10]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대전광역시', '광주광역시'], dtype='object')

In [11]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [12]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대전광역시    1229139
광주광역시     734988
Name: 여자인구수, dtype: int64

In [13]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404424  1668618  1735805
인천광역시  2947217  1476813  1470404

In [14]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [15]:
idx[1]

4

In [16]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [17]:
idx[-1::]

Int64Index([10], dtype='int64')

In [18]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [19]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


In [20]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])

print(idx1.append(idx2))

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')


In [32]:
print(idx1.difference(idx2))
print(idx1-idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2)

Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


<ipython-input-32-1ec45eef442a>:4: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(idx1 & idx2)
<ipython-input-32-1ec45eef442a>:6: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(idx1 | idx2)
<ipython-input-32-1ec45eef442a>:9: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(idx1 ^ idx2)


In [34]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [35]:
s['b']

0.25

In [37]:
'b' in s

True

In [38]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [39]:
s.items()

In [40]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [41]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [42]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[(s>0.4)&(s<0.8)]

c    0.50
d    0.75
dtype: float64

In [45]:
s[['a', 'b', 'c']]

a    0.00
b    0.25
c    0.50
dtype: float64

In [47]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
              index = [1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [48]:
s[1]

'a'

In [49]:
s[2:4]

5    c
7    d
dtype: object

In [50]:
s.iloc[1]

'b'

In [51]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [52]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [53]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

In [55]:
korea_df

인구수    남자인구수    여자인구수
서울특별시   9720846  4732275  4988571
부산광역시   3404424  1668618  1735805
인천광역시   2947217  1476813  1470404
대전광역시   1471040   734441  1229139
광주광역시  14455048   720060   734988

In [56]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [57]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [58]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대전광역시    1229139
광주광역시     734988
Name: 여자인구수, dtype: int64

In [59]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [60]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시   9720846  4732275  4988571   94.862336
부산광역시   3404424  1668618  1735805   96.129346
인천광역시   2947217  1476813  1470404  100.435867
대전광역시   1471040   734441  1229139   59.752477
광주광역시  14455048   720060   734988   97.968946

In [61]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442400e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [1.47104000e+06, 7.34441000e+05, 1.22913900e+06, 5.97524771e+01],
       [1.44550480e+07, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [62]:
korea_df.T

서울특별시         부산광역시         인천광역시         대전광역시         광주광역시
인구수    9.720846e+06  3.404424e+06  2.947217e+06  1.471040e+06  1.445505e+07
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  5.975248e+01  9.796895e+01

In [63]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [64]:
korea_df['인구수']

서울특별시     9720846
부산광역시     3404424
인천광역시     2947217
대전광역시     1471040
광주광역시    14455048
Name: 인구수, dtype: int64

In [65]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404424  1668618
인천광역시  2947217  1476813

In [66]:
korea_df.loc[(korea_df['여자인구수']>1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404424  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대전광역시  1471040   734441  1229139   59.752477

In [67]:
korea_df.loc[(korea_df.인구수<2000000)]

인구수   남자인구수    여자인구수       남여비율
대전광역시  1471040  734441  1229139  59.752477

In [68]:
korea_df.loc[(korea_df.인구수>2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시   9720846  4732275  4988571   94.862336
부산광역시   3404424  1668618  1735805   96.129346
인천광역시   2947217  1476813  1470404  100.435867
광주광역시  14455048   720060   734988   97.968946

In [69]:
korea_df.loc[(korea_df.남여비율>100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [71]:
korea_df.loc[(korea_df.인구수>2500000) & (korea_df.남여비율<100)]

인구수    남자인구수    여자인구수       남여비율
서울특별시   9720846  4732275  4988571  94.862336
부산광역시   3404424  1668618  1735805  96.129346
광주광역시  14455048   720060   734988  97.968946

In [72]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404424  1668618
인천광역시  2947217  1476813

In [74]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시   9720846  4732275  4988571   94.862336
부산광역시   3404424  1668618  1735805   96.129346
인천광역시   2947217  1476813  1470404  100.435867
대전광역시   1471040   734441  1229139   59.752477
광주광역시  14455048   720060   734988   97.968946

In [76]:
idx_tuple = [('서울특별시', 2010), ('서울특별시', 2020),
             ('부산광역시', 2010), ('부산광역시', 2020),
             ('인천광역시', 2010), ('인천광역시', 2020),
             ('대전광역시', 2010), ('대전광역시', 2020),
             ('광주광역시', 2010), ('광주광역시', 2020),
             ]
idx_tuple

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [78]:
pop_tuples = [10312545, 9720846,
              3567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuple)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     3567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대전광역시, 2010)     2511676
(대전광역시, 2020)     2427954
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [79]:
midx = pd.MultiIndex.from_tuples(idx_tuple)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [80]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대전광역시  2010     2511676
       2020     2427954
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [81]:
population[:, 2010]

서울특별시    10312545
부산광역시     3567910
인천광역시     2758296
대전광역시     2511676
광주광역시     1454636
dtype: int64

In [82]:
population['대전광역시', :]

2010    2511676
2020    2427954
dtype: int64

In [83]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대전광역시   2511676  2427954
부산광역시   3567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [84]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대전광역시  2010     2511676
       2020     2427954
부산광역시  2010     3567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [87]:
male_tuple = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              721780, 720560]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 721780,
 720560]

In [88]:
korea_mdf = pd.DataFrame({'총인구수':population,
                          '남자인구수':male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   3567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대전광역시 2010   2511676  1255245
      2020   2427954  1198815
광주광역시 2010   1454636   721780
      2020   1455048   720560

In [89]:
female_tuple = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                732856, 734988]
female_tuple

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 732856,
 734988]

In [90]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuple,
                          '여자인구수':female_tuple})
korea_mdf


총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   3567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대전광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
광주광역시 2010   1454636   721780   732856
      2020   1455048   720560   734988

In [92]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대전광역시  2010     99.905606
       2020     97.532907
광주광역시  2010     98.488653
       2020     98.036975
dtype: float64

In [93]:
ratio.unstack()

2010        2020
광주광역시   98.488653   98.036975
대전광역시   99.905606   97.532907
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [94]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuple,
                          '여자인구수': female_tuple,
                          '남여비율':ratio})
korea_mdf


총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대전광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720560   734988   98.036975

In [95]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index = [['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                  columns = ['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.675910  0.781185  0.498196
  2  0.697326  0.879335  0.947714
b 1  0.762119  0.834410  0.606313
  2  0.722053  0.816224  0.552991
c 1  0.767109  0.844818  0.142232
  2  0.562317  0.639250  0.956168

In [96]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])


MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [98]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [100]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [102]:
pd.MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
              codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [103]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대전광역시  2010     2511676
       2020     2427954
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [104]:
population.index.names = ['행정구역', '연도']
population

행정구역   연도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대전광역시  2010     2511676
       2020     2427954
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [105]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                 names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                  names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index = idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.97 -1.53 -0.30 -0.50  2.37 -1.79
      2      0.52  0.70  0.79 -0.85  2.16  0.21
b     1      0.40  0.22 -0.14  0.26 -0.41 -1.03
      2     -1.51 -1.41 -1.98  0.93 -1.51 -0.31
c     1      0.09  0.14 -0.15 -0.03 -0.83  1.00
      2     -1.51  0.95  0.26  0.83 -1.56  0.75

In [106]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.30 -0.50
      2      0.79 -0.85
b     1     -0.14  0.26
      2     -1.98  0.93
c     1     -0.15 -0.03
      2      0.26  0.83

In [107]:
population

행정구역   연도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대전광역시  2010     2511676
       2020     2427954
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [108]:
population['인천광역시', 2010]

2758296

In [109]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     3567910
인천광역시     2758296
대전광역시     2511676
광주광역시     1454636
dtype: int64

In [110]:
population[population>3000000]

행정구역   연도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
dtype: int64

In [112]:
population[['광주광역시', '대전광역시']]

행정구역   연도  
광주광역시  2010    1454636
       2020    1455048
대전광역시  2010    2511676
       2020    2427954
dtype: int64

In [113]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.97 -1.53 -0.30 -0.50  2.37 -1.79
      2      0.52  0.70  0.79 -0.85  2.16  0.21
b     1      0.40  0.22 -0.14  0.26 -0.41 -1.03
      2     -1.51 -1.41 -1.98  0.93 -1.51 -0.31
c     1      0.09  0.14 -0.15 -0.03 -0.83  1.00
      2     -1.51  0.95  0.26  0.83 -1.56  0.75

In [114]:
mdf['c2', 1]

name1  name2
a      1       -0.30
       2        0.79
b      1       -0.14
       2       -1.98
c      1       -0.15
       2        0.26
Name: (c2, 1), dtype: float64

In [115]:
mdf.iloc[:3, :3]

col_name1      c1          c2
col_name2       1     2     1
name1 name2                  
a     1     -0.97 -1.53 -0.30
      2      0.52  0.70  0.79
b     1      0.40  0.22 -0.14

In [116]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -0.30
       2        0.79
b      1       -0.14
       2       -1.98
c      1       -0.15
       2        0.26
Name: (c2, 1), dtype: float64

In [117]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      0.70 -0.85  0.21
b     2     -1.41  0.93 -0.31
c     2      0.95  0.83  0.75

In [118]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [119]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대전광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720560   734988   98.036975

In [121]:
# korea_mdf['서울특별시':'인천광역시']
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720560   734988   98.036975
대전광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [122]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [123]:
korea_mdf.unstack(level=0)

총인구수                                        남자인구수                    \
행정구역    광주광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대전광역시    부산광역시   
연도                                                                             
2010  1454636  2511676  3567910  10312545  2758296  721780  1255245  1773170   
2020  1455048  2427954  3404423   9720846  2947217  720560  1198815  1668618   

                         여자인구수                                           남여비율  \
행정구역    서울특별시    인천광역시   광주광역시    대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
연도                                                                              
2010  5111259  1390356  732856  1256431  1794740  5201286  1367940  98.488653   
2020  4732275  1476813  734988  1229139  1735805  4988571  1470404  98.036975   

                                                   
행정구역      대전광역시      부산광역시      서울특별시       인천광역시  
연도                                                 
2010  99.905606  98.798155  98.269140  101.638668  
2020  97.532907  96.129346  94.862336  100.435867

In [124]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
연도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720560   732856   734988   98.488653   
대전광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
부산광역시   3567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
연도           2020  
행정구역               
광주광역시   98.036975  
대전광역시   97.532907  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [125]:
korea_mdf.stack()

행정구역   연도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.205600e+05
             여자인구수    7.349880e+05
             남여비율     9.803697e+01
대전광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
부산광역시  2010  총인구수     3.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
       2020  총인구수     3.404423e+06
             남자인구수    1.668618e+06
             여자인구수    1.735805e+06
             남여비율     9.612935e+01
서울특별시  2010  총인구수     1.031254e+07
             남자인구수    5.111259e+06
             여자인구수    5.201286e+06
             남여비율     9.826914e+01
 

In [126]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720560   734988   98.036975
대전광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [127]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
연도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720560   734988   98.036975
2010  대전광역시   2511676  1255245  1256431   99.905606
2020  대전광역시   2427954  1198815  1229139   97.532907
2010  부산광역시   3567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [128]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    연도      총인구수    남자인구수    여자인구수        남여비율
0  광주광역시  2010   1454636   721780   732856   98.488653
1  광주광역시  2020   1455048   720560   734988   98.036975
2  대전광역시  2010   2511676  1255245  1256431   99.905606
3  대전광역시  2020   2427954  1198815  1229139   97.532907
4  부산광역시  2010   3567910  1773170  1794740   98.798155
5  부산광역시  2020   3404423  1668618  1735805   96.129346
6  서울특별시  2010  10312545  5111259  5201286   98.269140
7  서울특별시  2020   9720846  4732275  4988571   94.862336
8  인천광역시  2010   2758296  1390356  1367940  101.638668
9  인천광역시  2020   2947217  1476813  1470404  100.435867

In [129]:
idx_flat.set_index(['행정구역', '연도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720560   734988   98.036975
대전광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [131]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    7
1    6
2    3
3    8
4    7
dtype: int32

In [133]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns = ("a", 'b', 'c'))
df

a  b  c
0  9  3  5
1  4  4  4
2  8  6  6

In [134]:
np.exp(s)

0    1096.633158
1     403.428793
2      20.085537
3    2980.957987
4    1096.633158
dtype: float64

In [135]:
np.cos(df * np.pi / 4)

a             b             c
0  0.707107 -7.071068e-01 -7.071068e-01
1 -1.000000 -1.000000e+00 -1.000000e+00
2  1.000000 -1.836970e-16 -1.836970e-16

In [137]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [139]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [140]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                   columns = list('ACD'))
df1

A   C   D
0  4   1  14
1  1  12   0
2  9  13  13

In [141]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                   columns=list('BAECD'))
df2


B   A   E   C   D
0   6  13  13   3   2
1  10  19  15   3  15
2   3   9   9   9   8
3  11   7   7  19   6
4  19   1  19   5   7

In [142]:
df1 + df2

A   B     C     D   E
0  17.0 NaN   4.0  16.0 NaN
1  20.0 NaN  15.0  15.0 NaN
2  18.0 NaN  22.0  21.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [146]:
df1.stack()

0  A     4
   C     1
   D    14
1  A     1
   C    12
   D     0
2  A     9
   C    13
   D    13
dtype: int32

In [147]:
df1.sum()

A    14
C    26
D    27
dtype: int64

In [145]:
df1.stack().mean()

7.444444444444445

In [143]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  17.000000  13.444444   4.000000  16.000000  20.444444
1  20.000000  17.444444  15.000000  15.000000  22.444444
2  18.000000  10.444444  22.000000  21.000000  16.444444
3  14.444444  18.444444  26.444444  13.444444  14.444444
4   8.444444  26.444444  12.444444  14.444444  26.444444

In [148]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[5, 2, 1],
       [4, 6, 9],
       [1, 3, 8]])

In [150]:
print(a)
print(a[0])
k = a + a[0]
print(k)

[[5 2 1]
 [4 6 9]
 [1 3 8]]
[5 2 1]
[[10  4  2]
 [ 9  8 10]
 [ 6  5  9]]


In [151]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [152]:
df + df.iloc[0]

A  B   C
0  10  4   2
1   9  8  10
2   6  5   9

In [153]:
df.add(df.iloc[0])

A  B   C
0  10  4   2
1   9  8  10
2   6  5   9

In [154]:
a

array([[5, 2, 1],
       [4, 6, 9],
       [1, 3, 8]])

In [155]:
a - a[0]

array([[ 0,  0,  0],
       [-1,  4,  8],
       [-4,  1,  7]])

In [156]:
df - df.iloc[0]

A  B  C
0  0  0  0
1 -1  4  8
2 -4  1  7

In [157]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -1  4  8
2 -4  1  7

In [160]:
df.subtract(df['B'], axis=0)

A  B  C
0  3  0 -1
1 -2  0  3
2 -2  0  5

In [161]:
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [162]:
a

array([[5, 2, 1],
       [4, 6, 9],
       [1, 3, 8]])

In [163]:
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [164]:
a * a[0]

array([[25,  4,  1],
       [20, 12,  9],
       [ 5,  6,  8]])

In [165]:
df * df.iloc[1]

A   B   C
0  20  12   9
1  16  36  81
2   4  18  72

In [166]:
a * a[1]

array([[20, 12,  9],
       [16, 36, 81],
       [ 4, 18, 72]])

In [167]:
df.mul(df.iloc[1])

A   B   C
0  20  12   9
1  16  36  81
2   4  18  72

In [169]:
df.multiply(df.iloc[2])

A   B   C
0  5   6   8
1  4  18  72
2  1   9  64

In [170]:
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [171]:
a

array([[5, 2, 1],
       [4, 6, 9],
       [1, 3, 8]])

In [172]:
a / a[0]

array([[1. , 1. , 1. ],
       [0.8, 3. , 9. ],
       [0.2, 1.5, 8. ]])

In [173]:
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [174]:
df / df.iloc[0]

A    B    C
0  1.0  1.0  1.0
1  0.8  3.0  9.0
2  0.2  1.5  8.0

In [175]:
df.truediv(df.iloc[0])

A    B    C
0  1.0  1.0  1.0
1  0.8  3.0  9.0
2  0.2  1.5  8.0

In [176]:
df.div(df.iloc[0])

A    B    C
0  1.0  1.0  1.0
1  0.8  3.0  9.0
2  0.2  1.5  8.0

In [177]:
df.divide(df.iloc[0])

A    B    C
0  1.0  1.0  1.0
1  0.8  3.0  9.0
2  0.2  1.5  8.0

In [178]:
a // a[0]

array([[1, 1, 1],
       [0, 3, 9],
       [0, 1, 8]], dtype=int32)

In [179]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  0  3  9
2  0  1  8

In [180]:
a

array([[5, 2, 1],
       [4, 6, 9],
       [1, 3, 8]])

In [181]:
a % a[0]

array([[0, 0, 0],
       [4, 0, 0],
       [1, 1, 0]], dtype=int32)

In [182]:
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [183]:
df % df.iloc[0]

A  B  C
0  0  0  0
1  4  0  0
2  1  1  0

In [184]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  4  0  0
2  1  1  0

In [185]:
df.pow(df.iloc[0])

A   B  C
0  3125   4  1
1  1024  36  9
2     1   9  8

In [186]:
pow(5, 5)

3125

In [187]:
row = df.iloc[0, ::2]
row

A    5
C    1
Name: 0, dtype: int32

In [189]:
df

A  B  C
0  5  2  1
1  4  6  9
2  1  3  8

In [188]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -1.0 NaN  8.0
2 -4.0 NaN  7.0

In [190]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [191]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [192]:
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [193]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [194]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index=[2, 4, 1, 3],
                  columns=list('BDAC'))
df

B  D  A  C
2  5  1  3  0
4  7  8  4  6
1  4  6  9  6
3  0  6  1  7

In [195]:
df.sort_index()

B  D  A  C
1  4  6  9  6
2  5  1  3  0
3  0  6  1  7
4  7  8  4  6

In [196]:
df.sort_values(by='A')

B  D  A  C
3  0  6  1  7
2  5  1  3  0
4  7  8  4  6
1  4  6  9  6

In [197]:
df.sort_values(by=['A', 'C'])

B  D  A  C
3  0  6  1  7
2  5  1  3  0
4  7  8  4  6
1  4  6  9  6

In [198]:
df.sort_index()

B  D  A  C
1  4  6  9  6
2  5  1  3  0
3  0  6  1  7
4  7  8  4  6

In [199]:
df.sort_index(axis=1)

A  B  C  D
2  3  5  0  1
4  4  7  6  8
1  9  4  6  6
3  1  0  7  6

In [200]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [201]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [202]:
s.rank(method='first')

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [204]:
s.rank(method='max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64