In [1]:
import numpy as np

In [4]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

In [5]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [6]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]    
])


In [7]:
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [8]:
C = np.random.rand(3, 5)
C

array([[0.77508747, 0.19102666, 0.45171193, 0.48638947, 0.6927492 ],
       [0.24162042, 0.58569755, 0.35145788, 0.69567793, 0.26253565],
       [0.16494605, 0.410385  , 0.24975823, 0.54324864, 0.21206957]])

In [11]:
D = np.zeros((2, 4))

In [12]:
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [14]:
A[0][2]

2