In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]    
])


In [5]:
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [6]:
C = np.random.rand(3, 5)
C

array([[0.84844559, 0.97418454, 0.05024993, 0.55029712, 0.97981568],
       [0.14525724, 0.66395878, 0.27470583, 0.77933643, 0.49563606],
       [0.88021101, 0.27029688, 0.70868084, 0.86749789, 0.07184714]])

In [7]:
D = np.zeros((2, 4))

In [8]:
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [10]:
A[0][2]

2

In [11]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [12]:
B = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])


In [13]:
A * B

array([[ 0,  2,  6],
       [ 8,  0,  6],
       [ 7, 16,  0]])

In [14]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])


In [15]:
B = np.random.rand(3, 3)

In [16]:
A + B

array([[ 1.51854312, -0.98533808,  2.52931823],
       [ 3.53660348,  2.92768624,  2.2897967 ],
       [ 4.73548889,  1.29064629,  2.98163409]])

In [17]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [18]:
np.dot(A, B)

array([[ 1.45291741, -0.33173174,  2.20278972],
       [ 4.09981408,  2.48065083,  4.13081629],
       [ 4.08175372,  1.56762651,  4.37033782]])

In [19]:
A @ B

array([[ 1.45291741, -0.33173174,  2.20278972],
       [ 4.09981408,  2.48065083,  4.13081629],
       [ 4.08175372,  1.56762651,  4.37033782]])

In [20]:
A @ B + (A + 2 * B)

array([[ 3.49000365, -1.3024079 ,  5.26142619],
       [ 8.17302104,  6.33602332,  6.71040968],
       [ 9.55273149,  3.14891909,  8.33360601]])

In [21]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])


In [22]:
a_transpose = np.transpose(A)

In [23]:
a_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [24]:
A.T

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [25]:
list(zip(*A))

[(1, 3, 4), (-1, 2, 1), (2, 2, 2)]

In [27]:
k = list(zip(*A))
k

[(1, 3, 4), (-1, 2, 1), (2, 2, 2)]

In [29]:
np.array(list(zip(*k)))

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [30]:
k = [[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]]

In [31]:
k

[[1, -1, 2], [3, 2, 2], [4, 1, 2]]

In [33]:
j = list(zip(*k))

In [34]:
type(j), type(j[0])

(list, tuple)

In [38]:
list(zip(*j))

[(1, -1, 2), (3, 2, 2), (4, 1, 2)]

In [39]:
j[0] = list(j[0])

In [40]:
j

[[1, 3, 4], (-1, 2, 1), (2, 2, 2)]

In [41]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [42]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [45]:
A_inv = np.linalg.pinv(A)

In [46]:
A_inv @ A

array([[ 1.00000000e+00,  1.11022302e-16, -2.22044605e-16],
       [-4.44089210e-16,  1.00000000e+00, -4.44089210e-16],
       [-8.88178420e-16, -2.22044605e-16,  1.00000000e+00]])