In [1]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

In [2]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BAUM\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [4]:
example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english')) 

word_tokens = word_tokenize(example)

result = []
for word in word_tokens: 
    if word not in stop_words: 
        result.append(word) 

print('불용어 제거 전 :',word_tokens) 
print('불용어 제거 후 :',result)

불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [5]:
okt = Okt()

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 :',word_tokens) 
print('불용어 제거 후 :',result)

불용어 제거 전 : ['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']
불용어 제거 후 : ['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨대', '삼겹살', '을', '중요한', '있지', '.']


In [6]:
import re

In [7]:
r = re.compile('a.c')
r.search('kkk')

In [8]:
r.search('abc')

<re.Match object; span=(0, 3), match='abc'>

In [9]:
r = re.compile(('ab?c'))

In [10]:
r.search('abbc')

In [11]:
r.search('abc')

<re.Match object; span=(0, 3), match='abc'>

In [12]:
r.search("ac")


<re.Match object; span=(0, 2), match='ac'>

In [13]:
r = re.compile("ab*c")
r.search("a")

In [14]:
r.search("ac")


<re.Match object; span=(0, 2), match='ac'>

In [15]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [16]:
r.search("abbbbc")


<re.Match object; span=(0, 6), match='abbbbc'>

In [17]:
r = re.compile("ab+c")
r.search("ac")


In [18]:
r.search("abc")


<re.Match object; span=(0, 3), match='abc'>

In [19]:
r.search("abbbbc")


<re.Match object; span=(0, 6), match='abbbbc'>

In [20]:
r = re.compile("^ab")


In [21]:
r.search("bbc")


In [22]:
r.search("zab")


In [23]:
r.search("abz")


<re.Match object; span=(0, 2), match='ab'>

In [24]:
r = re.compile("ab{2}c")


In [25]:
r.search("ac")
r.search("abc")
r.search("abbbbbc")
r.search("abbc")


<re.Match object; span=(0, 4), match='abbc'>

In [26]:
r = re.compile("ab{2,8}c")
r.search("ac")
r.search("abc")
r.search("abbbbbbbbbc")

r.search("abbbbbbbbc")


<re.Match object; span=(0, 10), match='abbbbbbbbc'>

In [27]:
r.search("abbc")


<re.Match object; span=(0, 4), match='abbc'>

In [28]:
r = re.compile("a{2,}bc")


In [29]:
r.search("aabc")


<re.Match object; span=(0, 4), match='aabc'>

In [30]:
r.search("aaaaaaaabc")


<re.Match object; span=(0, 10), match='aaaaaaaabc'>

In [31]:
r = re.compile("[abc]")


In [32]:
r.search("zzz")


In [33]:
r.search("a")


<re.Match object; span=(0, 1), match='a'>

In [34]:
r.search("aaaaaaa")


<re.Match object; span=(0, 1), match='a'>

In [35]:
r.search("baac")


<re.Match object; span=(0, 1), match='b'>

In [36]:
r = re.compile("[a-z]")


In [37]:
r.search("AAA")


In [38]:
r.search("111")


In [39]:
r.search("aBC")


<re.Match object; span=(0, 1), match='a'>

In [40]:
r = re.compile("[^abc]")


In [41]:
r.search("a")


In [42]:
r.search("a")
r.search("ab")
r.search("b")


In [43]:
r.search("d")


<re.Match object; span=(0, 1), match='d'>

In [44]:
r.search("1")


<re.Match object; span=(0, 1), match='1'>

In [45]:
r = re.compile("ab.")


In [46]:
r.match("kkkabc")


In [47]:
r.search("kkkabc")


<re.Match object; span=(3, 6), match='abc'>

In [48]:
r.match("abckkk")


<re.Match object; span=(0, 3), match='abc'>

In [49]:
text = "사과 딸기 수박 메론 바나나"
re.split(" ", text)

['사과', '딸기', '수박', '메론', '바나나']

In [50]:
text = """사과
딸기
수박
메론
바나나"""

re.split("\n", text)


['사과', '딸기', '수박', '메론', '바나나']

In [51]:
text = "사과+딸기+수박+메론+바나나"

re.split("\+", text)


['사과', '딸기', '수박', '메론', '바나나']

In [52]:
text = """이름 : 김철수
전화번호 : 010 - 1234 - 1234
나이 : 30
성별 : 남"""

re.findall("\d+", text)

['010', '1234', '1234', '30']

In [53]:
re.findall("\d+", "문자열입니다.")


[]

In [54]:
text = "Regular expression : A regular expression, regex or regexp[1] (sometimes called a rational expression)[2][3] is, in theoretical computer science and formal language theory, a sequence of characters that define a search pattern."

preprocessed_text = re.sub('[^a-zA-Z]', ' ', text)
print(preprocessed_text)


Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern 


In [55]:
text = """100 John    PROF
101 James   STUD
102 Mac   STUD"""


In [56]:
re.split('\s+', text)


['100', 'John', 'PROF', '101', 'James', 'STUD', '102', 'Mac', 'STUD']

In [57]:
re.findall('\d+',text) 

['100', '101', '102']

In [58]:
re.findall('[A-Z]', text)

['J', 'P', 'R', 'O', 'F', 'J', 'S', 'T', 'U', 'D', 'M', 'S', 'T', 'U', 'D']

In [59]:
re.findall('[A-Z]{4}', text)

['PROF', 'STUD', 'STUD']

In [60]:
re.findall('[A-Z][a-z]+', text)

['John', 'James', 'Mac']

In [61]:
from nltk.tokenize import RegexpTokenizer

text = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop"

tokenizer1 = RegexpTokenizer("[\w]+")
tokenizer2 = RegexpTokenizer("\s+", gaps=True)

print(tokenizer1.tokenize(text))
print(tokenizer2.tokenize(text))


['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'Mr', 'Jone', 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name,', 'Mr.', "Jone's", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [62]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [63]:
raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."


In [64]:
sentences = sent_tokenize(raw_text)
print(sentences)


['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [65]:
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []

    for word in tokenized_sentence:
        word = word.lower()  # 모든 단어를 소문자화하여 단어의 개수를 줄인다.
        if word not in stop_words:  # 단어 토큰화 된 결과에 대해서 불용어를 제거한다.
            if len(word) > 2:  # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거한다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0
                vocab[word] += 1
    preprocessed_sentences.append(result)
print(preprocessed_sentences)


[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [66]:
print('단어 집합 :',vocab)

단어 집합 : {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [67]:
print(vocab["barber"])


8


In [68]:
vocab_sorted = sorted(vocab.items(), key=lambda x: x[1], reverse=True)
print(vocab_sorted)


[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [69]:
word_to_index = {}
i = 0
for (word, frequency) in vocab_sorted:
    if frequency > 1:  # 빈도수가 작은 단어는 제외.
        i = i + 1
        word_to_index[word] = i

print(word_to_index)


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [70]:
vocap_size = 5

words_frequency = [word for word, index in word_to_index.items() if index >= vocap_size + 1]


In [71]:
words_frequency

['word', 'keeping']

In [72]:
for w in words_frequency:
    del word_to_index[w]


In [73]:
word_to_index


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [74]:
word_to_index['OOV'] = len(word_to_index) + 1
word_to_index

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}

In [75]:
encoded_sentences = []
for sentence in preprocessed_sentences:
    encoded_sentence = []
    for word in sentence:
        try:
            encoded_sentence.append(word_to_index[word])
        except KeyError:
            encoded_sentence.append(word_to_index['OOV'])
    encoded_sentences.append(encoded_sentence)
encoded_sentences

[[1, 5],
 [1, 6, 5],
 [1, 3, 5],
 [6, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [6, 6, 3, 2, 6, 1, 6],
 [1, 6, 3, 6]]

In [76]:
from collections import Counter

In [77]:
preprocessed_sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [78]:
all_words_list = sum(preprocessed_sentences, [])
all_words_list

['barber',
 'person',
 'barber',
 'good',
 'person',
 'barber',
 'huge',
 'person',
 'knew',
 'secret',
 'secret',
 'kept',
 'huge',
 'secret',
 'huge',
 'secret',
 'barber',
 'kept',
 'word',
 'barber',
 'kept',
 'word',
 'barber',
 'kept',
 'secret',
 'keeping',
 'keeping',
 'huge',
 'secret',
 'driving',
 'barber',
 'crazy',
 'barber',
 'went',
 'huge',
 'mountain']

In [79]:
vocab = Counter(all_words_list)
vocab

Counter({'barber': 8,
         'person': 3,
         'good': 1,
         'huge': 5,
         'knew': 1,
         'secret': 6,
         'kept': 4,
         'word': 2,
         'keeping': 2,
         'driving': 1,
         'crazy': 1,
         'went': 1,
         'mountain': 1})

In [80]:
vocab['barber']

8

In [81]:
vocab_size = 5
vocab = vocab.most_common(vocab_size)

In [82]:
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [83]:
word_to_index = {}
i = 0
for (word, frequency) in vocab:
    i += 1
    word_to_index[word] = i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [84]:
from nltk import FreqDist
import numpy as np

In [85]:
vocab = FreqDist(np.hstack(preprocessed_sentences))

In [86]:
vocab

FreqDist({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, ...})

In [87]:
preprocessed_sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [88]:
np.hstack(preprocessed_sentences)

array(['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge',
       'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret',
       'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept',
       'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge',
       'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge',
       'mountain'], dtype='<U8')

In [89]:
vocab_size = 5
vocab = vocab.most_common(vocab_size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [90]:
word_to_index = {word[0]:index+1 for index, word in enumerate(vocab)}
word_to_index

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [91]:
test_input = ['a', 'b', 'c', 'd', 'e']
for index, value in enumerate(test_input):
    print(value, index)

a 0
b 1
c 2
d 3
e 4


In [92]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [93]:
preprocessed_sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [94]:
tokenizer = Tokenizer()

In [95]:
tokenizer.fit_on_texts(preprocessed_sentences)

In [96]:
tokenizer.word_index

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7,
 'good': 8,
 'knew': 9,
 'driving': 10,
 'crazy': 11,
 'went': 12,
 'mountain': 13}

In [97]:
tokenizer.word_counts

OrderedDict([('barber', 8),
             ('person', 3),
             ('good', 1),
             ('huge', 5),
             ('knew', 1),
             ('secret', 6),
             ('kept', 4),
             ('word', 2),
             ('keeping', 2),
             ('driving', 1),
             ('crazy', 1),
             ('went', 1),
             ('mountain', 1)])

In [98]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [99]:
vocab_size = 5
tokenizer = Tokenizer(num_words=vocab_size + 1)
tokenizer.fit_on_texts(preprocessed_sentences)

In [100]:
tokenizer.word_index

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7,
 'good': 8,
 'knew': 9,
 'driving': 10,
 'crazy': 11,
 'went': 12,
 'mountain': 13}

In [101]:
tokenizer.word_counts

OrderedDict([('barber', 8),
             ('person', 3),
             ('good', 1),
             ('huge', 5),
             ('knew', 1),
             ('secret', 6),
             ('kept', 4),
             ('word', 2),
             ('keeping', 2),
             ('driving', 1),
             ('crazy', 1),
             ('went', 1),
             ('mountain', 1)])

In [102]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [103]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)

In [106]:
tokenizer.word_index

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7,
 'good': 8,
 'knew': 9,
 'driving': 10,
 'crazy': 11,
 'went': 12,
 'mountain': 13}

In [104]:
vocab_size = 5
words_frequency = [word for word, index in tokenizer.word_index.items() if index >= vocab_size+1]

In [105]:
words_frequency

['word', 'keeping', 'good', 'knew', 'driving', 'crazy', 'went', 'mountain']

In [107]:
for word in words_frequency:
    del tokenizer.word_index[word]
    del tokenizer.word_counts[word]

In [108]:
tokenizer.word_index

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [109]:
tokenizer.word_counts

OrderedDict([('barber', 8),
             ('person', 3),
             ('huge', 5),
             ('secret', 6),
             ('kept', 4)])

In [110]:
tokenizer.texts_to_sequences(preprocessed_sentences)

[[1, 5],
 [1, 5],
 [1, 3, 5],
 [2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4],
 [1, 4],
 [1, 4, 2],
 [3, 2, 1],
 [1, 3]]

In [111]:
vocab_size = 5
tokenizer = Tokenizer(num_words=vocab_size+2, oov_token='OOV')
tokenizer.fit_on_texts(preprocessed_sentences)

In [112]:
tokenizer.word_index

{'OOV': 1,
 'barber': 2,
 'secret': 3,
 'huge': 4,
 'kept': 5,
 'person': 6,
 'word': 7,
 'keeping': 8,
 'good': 9,
 'knew': 10,
 'driving': 11,
 'crazy': 12,
 'went': 13,
 'mountain': 14}

In [113]:
tokenizer.texts_to_sequences(preprocessed_sentences)

[[2, 6],
 [2, 1, 6],
 [2, 4, 6],
 [1, 3],
 [3, 5, 4, 3],
 [4, 3],
 [2, 5, 1],
 [2, 5, 1],
 [2, 5, 3],
 [1, 1, 4, 3, 1, 2, 1],
 [2, 1, 4, 1]]

In [114]:
import numpy as np

In [115]:
preprocessed_sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [116]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)

In [117]:
tokenizer

In [118]:
print(tokenizer.fit_on_texts(preprocessed_sentences))


None


In [120]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [121]:
max_len = max(len(item) for item in encoded)
max_len

7

In [122]:
for sentence in encoded:
    while len(sentence) < max_len:
        sentence.append(0)
padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [123]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [124]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [126]:
padded = pad_sequences(encoded, padding='post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [128]:
(padded == padded_np).all()

True

In [129]:
padded = pad_sequences(encoded, padding='post', maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]])

In [130]:
padded = pad_sequences(encoded, padding='post', truncating='post', maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]])

In [131]:
last_value = len(tokenizer.word_index)+1
last_value

14

In [132]:
padded = pad_sequences(encoded, padding='post', value=last_value)
padded

array([[ 1,  5, 14, 14, 14, 14, 14],
       [ 1,  8,  5, 14, 14, 14, 14],
       [ 1,  3,  5, 14, 14, 14, 14],
       [ 9,  2, 14, 14, 14, 14, 14],
       [ 2,  4,  3,  2, 14, 14, 14],
       [ 3,  2, 14, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  2, 14, 14, 14, 14],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14, 14, 14]])

In [133]:
from konlpy.tag import Okt
okt = Okt()
tokens = okt.morphs('나는 자연어 처리를 배운다')
tokens

['나', '는', '자연어', '처리', '를', '배운다']

In [134]:
word_to_index = {word: index for index, word in enumerate(tokens)}
word_to_index

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}

In [135]:
def one_hot_encoding(word, word_to_index):
    one_hot_vector = [0] * len(word_to_index)
    index = word_to_index[word]
    one_hot_vector[index] = 1
    return one_hot_vector


In [137]:
word

'mountain'

In [138]:
one_hot_encoding('자연어', word_to_index)

[0, 0, 1, 0, 0, 0]

In [139]:
text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

In [140]:
from tensorflow.keras.utils import to_categorical

In [141]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

In [142]:
tokenizer.word_index

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}

In [143]:
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"

In [144]:
encoded = tokenizer.texts_to_sequences([sub_text])[0]
encoded

[2, 5, 1, 6, 3, 7]

In [145]:
one_hot = to_categorical(encoded)
one_hot

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [149]:
sequences = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)

In [151]:
X

('a', 'b', 'c')

In [152]:
y

(1, 2, 3)

In [153]:
values = [['당신에게 드리는 마지막 혜택!', 1],
          ['내일 뵐 수 있을지 확인 부탁드...', 0],
          ['도연씨. 잘 지내시죠? 오랜만입...', 0],
          ['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']


In [154]:
import pandas as pd

In [155]:
df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [156]:
x = df['메일 본문']
y = df['스팸 메일 유무']

In [166]:
x.to_list()

['당신에게 드리는 마지막 혜택!',
 '내일 뵐 수 있을지 확인 부탁드...',
 '도연씨. 잘 지내시죠? 오랜만입...',
 '(광고) AI로 주가를 예측할 수 있다!']

In [167]:
print(y.to_list())

[1, 0, 0, 1]


In [168]:
np_array = np.arange(0,16).reshape((4,4))
print(np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [169]:
x = np_array[:, :3]
y = np_array[:, 3]

In [170]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [171]:
y

array([ 3,  7, 11, 15])

In [172]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=1234)

In [173]:
x, y = np.arange(10).reshape((5,2)), range(5)

In [174]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [176]:
list(y)

[0, 1, 2, 3, 4]

In [181]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1234)

In [182]:
x_train

array([[2, 3],
       [4, 5],
       [6, 7]])

In [183]:
x_test

array([[8, 9],
       [0, 1]])

In [184]:
y_train

[1, 2, 3]

In [185]:
y_test

[4, 0]

In [186]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [187]:
x_train

array([[8, 9],
       [0, 1],
       [6, 7]])

In [188]:
y_train

[4, 0, 3]

In [189]:
x, y = np.arange(0,24).reshape((12,2)), range(12)

In [190]:
num_of_train = int(len(x)*0.8)
num_of_test = int(len(x)- num_of_train)

In [191]:
x_test = x[num_of_train:]
y_test = y[num_of_train:]
x_train = x[:num_of_train]
y_train = y[:num_of_train]

In [192]:
x_test

array([[18, 19],
       [20, 21],
       [22, 23]])

In [193]:
x_train

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [194]:
y_test

range(9, 12)

In [195]:
y_train

range(0, 9)